//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoConnectWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLDTvXTEntities : DbContext
    {
        public QLDTvXTEntities()
            : base("name=QLDTvXTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BACHOC> BACHOC { get; set; }
        public virtual DbSet<BoGD> BoGD { get; set; }
        public virtual DbSet<DIEMMH> DIEMMH { get; set; }
        public virtual DbSet<HOCSINH> HOCSINH { get; set; }
        public virtual DbSet<KHOI> KHOI { get; set; }
        public virtual DbSet<KHUVUC> KHUVUC { get; set; }
        public virtual DbSet<MONHOC> MONHOC { get; set; }
        public virtual DbSet<NGANHXT> NGANHXT { get; set; }
        public virtual DbSet<NGUYENVONG> NGUYENVONG { get; set; }
        public virtual DbSet<PHANQUYEN> PHANQUYEN { get; set; }
        public virtual DbSet<PHANHOI> PHANHOI { get; set; }
        public virtual DbSet<SoGD> SoGD { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<THPT> THPT { get; set; }
        public virtual DbSet<TRUONGDH> TRUONGDH { get; set; }
    }
}
