//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoConnectWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHOI()
        {
            this.NGUYENVONG = new HashSet<NGUYENVONG>();
        }
    
        public string MaKhoi { get; set; }
        public string MonHoc1 { get; set; }
        public string MonHoc2 { get; set; }
        public string MonHoc3 { get; set; }
    
        public virtual MONHOC MONHOC { get; set; }
        public virtual MONHOC MONHOC4 { get; set; }
        public virtual MONHOC MONHOC5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUYENVONG> NGUYENVONG { get; set; }
    }
}
