//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoConnectWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGANHXT
    {
        public string UUID { get; set; }
        public string MaTruong { get; set; }
        public string MaNganh { get; set; }
        public string TenNganh { get; set; }
        public int NamXT { get; set; }
        public string MaBH { get; set; }
        public Nullable<int> DiemChuan { get; set; }
    
        public virtual BACHOC BACHOC { get; set; }
        public virtual TRUONGDH TRUONGDH { get; set; }
    }
}
