//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoConnectWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUYENVONG
    {
        public string UUIDNganh { get; set; }
        public string MaBH { get; set; }
        public string MaKhoi { get; set; }
        public string MaHS { get; set; }
    
        public virtual BACHOC BACHOC { get; set; }
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual KHOI KHOI { get; set; }
    }
}
